# swc: Makefile.common

.PHONY: check-dependencies-$(dir)
check-dependencies-$(dir):

.PHONY: build-$(dir)
build-$(dir): $($(dir)_TARGETS)

.PHONY: install-$(dir)
install-$(dir):

.deps/$(dir):
	@mkdir -p "$@"

CLEAN_FILES += $($(dir)_TARGETS)

