# swc: Makefile.common

.PHONY: check-dependencies-$(dir)
check-dependencies-$(dir):

.PHONY: build-$(dir)
build-$(dir): $($(dir)_TARGETS)

.PHONY: install-$(dir)
install-$(dir):

.deps/$(dir):
	@mkdir -p "$@"

$(dir)/%.o: $(dir)/%.c | .deps/$(dir)
	$(compile) $($(@D)_CFLAGS) $($(@D)_PACKAGE_CFLAGS)

$(dir)/%.lo: $(dir)/%.c | .deps/$(dir)
	$(compile) -fPIC $($(@D)_CFLAGS) $($(@D)_PACKAGE_CFLAGS)

CLEAN_FILES += $($(dir)_TARGETS)

