# swc: protocol/Makefile.local

dir := protocol

PROTOCOL_EXTENSIONS =   \
    $(dir)/wayland-drm.xml

$(dir)/%-protocol.c: $(dir)/%.xml
	$(call quiet,GEN,$(WAYLAND_SCANNER)) code < $< > $@

$(dir)/%-server-protocol.h: $(dir)/%.xml
	$(call quiet,GEN,$(WAYLAND_SCANNER)) server-header < $< > $@

CLEAN_FILES +=                                          \
    $(PROTOCOL_EXTENSIONS:%.xml=%-protocol.c)           \
    $(PROTOCOL_EXTENSIONS:%.xml=%-server-protocol.h)

include Makefile.common

